version: '3.8'

services:

  db:
    image: mongo:4.2.8-bionic
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - SETGID
      - SETUID

  server:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    cap_drop:
      - ALL
    ports:
      - '80:3000'
    command: [
      '--port', '3000',
      '--static-root', '/code/packages/dashboard/out',
      '--db-connection-uri', 'mongodb://db:27017/innolens',
      '--models-uri', 'http://models:5000'
    ]

  models:
    build:
      context: .
      dockerfile: ./Dockerfile.models
    cap_drop:
      - ALL
    command: [
      '--port', '5000'
    ]
